/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lib.management;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import static lib.management.MyVariables.PASSWORD;
import static lib.management.MyVariables.PATH;
import static lib.management.MyVariables.PLACE;
import static lib.management.MyVariables.USERNAME;
public class InchargeSignup extends javax.swing.JInternalFrame {

    File myfile;
    String imagename;/**
     * Creates new form InchargeSignup
     */
    public InchargeSignup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        t2 = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        t3 = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        t4 = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        t5 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        t6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        t7 = new javax.swing.JRadioButton();
        t8 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setTitle("Incharge Signup");
        getContentPane().setLayout(null);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102), new java.awt.Color(102, 102, 102)));
        jPanel1.setName("Sign Up"); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(514, 450));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel1.setText("UserName");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(73, 104, 80, 26);
        jPanel1.add(t1);
        t1.setBounds(218, 104, 206, 22);

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel2.setText("Contact No.");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(73, 153, 90, 26);

        t2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jPanel1.add(t2);
        t2.setBounds(218, 153, 206, 22);

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel3.setText("Age");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(73, 198, 50, 20);

        t3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jPanel1.add(t3);
        t3.setBounds(218, 198, 206, 22);

        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel4.setText("Password");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(73, 244, 90, 26);
        jPanel1.add(t4);
        t4.setBounds(218, 244, 206, 22);

        jLabel5.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel5.setText("Re - Password");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(73, 290, 120, 26);

        t5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t5ActionPerformed(evt);
            }
        });
        t5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t5KeyPressed(evt);
            }
        });
        jPanel1.add(t5);
        t5.setBounds(218, 290, 206, 22);

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\THE BAD GUY\\Documents\\NetBeansProjects\\lib management\\signup.png")); // NOI18N
        jButton1.setText("SIGN UP");
        jButton1.setActionCommand("  SIGN UP");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(120, 380, 161, 72);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel6.setText("ADD INCHARGE");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(160, 30, 310, 43);

        t6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(t6);
        t6.setBounds(470, 100, 160, 190);

        jButton2.setText("Upload");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(470, 320, 160, 25);

        jLabel9.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel9.setText("Gender");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(70, 330, 110, 26);

        buttonGroup1.add(t7);
        t7.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        t7.setText("Male");
        t7.setContentAreaFilled(false);
        jPanel1.add(t7);
        t7.setBounds(220, 330, 90, 35);

        buttonGroup1.add(t8);
        t8.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        t8.setText("Female");
        t8.setContentAreaFilled(false);
        jPanel1.add(t8);
        t8.setBounds(320, 330, 100, 35);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("*  Img Size must be b/w 10kb to 900kb.");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(370, 400, 300, 17);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setText("*  Img Must be Cleared not Blured.");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(370, 420, 280, 16);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/adminsignup.jpg"))); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(0, 0, 670, 490);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(30, 40, 670, 490);
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 40, 150, 0);

        setBounds(0, 0, 760, 616);
    }// </editor-fold>//GEN-END:initComponents

    private void t5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t5ActionPerformed

    private void t5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t5KeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            jButton1.doClick();
        }
    }//GEN-LAST:event_t5KeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean flag=false;
 
        if(myfile!=null)
        {
            if(myfile.length()<900000&&myfile.length()>10000)
            {
                imagename=new java.util.Date().getTime() + myfile.getName();
                int i;

                FileInputStream rd = null;
                FileOutputStream outs = null;

                try 
                {
                    rd = new FileInputStream(myfile);
                    outs = new FileOutputStream("memberimages\\"+imagename);//writing the new file in 'Images' folder, in the project
                    byte[] b = new byte[2048]; //cache of 2kb
                    while ((i = rd.read(b)) !=-1) 
                    {
                        outs.write(b, 0, i); //copying from pictures to empimages byte by byte
                    }
                }
                catch (Exception e) 
                {
                    JOptionPane.showMessageDialog(rootPane, "error" + e.getMessage());
                } 
                    flag=true;
            }
            else
            {
                flag=false;
            }
        }
        else
        {
            if(t7.isSelected())
                imagename="defaultmale.jpg";
            else if(t8.isSelected())
                imagename="defaultfemale.png";
            flag=true;
        } 



        if(flag)
        {
            if(t4.getText().matches(t5.getText()))
            {
                try
                {
                    Connection myconnection=DriverManager.getConnection(PATH+PLACE,USERNAME,PASSWORD);
                    try
                    {
                        String myquery="insert into signup(name,contactno,age,password,usertype,gender,namepic) values(?,?,?,?,?,?,?)";
                        PreparedStatement mystatement=myconnection.prepareStatement(myquery);
                        mystatement.setString(1, t1.getText());
                        mystatement.setString(2, t2.getText());
                        mystatement.setString(3, t3.getText());
                        mystatement.setString(4, t4.getText());
                        mystatement.setString(5, "Incharge");
                        if(t7.isSelected())
                            mystatement.setString(6, "Male");
                        else if(t8.isSelected())
                            mystatement.setString(6, "Female");
                        mystatement.setString(7, imagename);
                        if(mystatement.executeUpdate()>0)
                        {
                            JOptionPane.showMessageDialog(rootPane, "Thanks For Signing Up");
                            InchargeFrame obj=new InchargeFrame();
                            obj.setVisible(true);
                            this.dispose();
                        }
                        else
                        {
                            JOptionPane.showMessageDialog(rootPane, "Some Problem Occured");
                        }
                    }
                    catch(Exception et)
                    {
                        JOptionPane.showMessageDialog(rootPane, "Error in querry due to "+et.getMessage());
                    }
                    finally
                    {
                        myconnection.close();
                    }
                }
                catch(Exception e)
                {
                    JOptionPane.showMessageDialog(rootPane, "Error in connection due to "+e.getMessage());
                }
            }
            else
            {
                JOptionPane.showMessageDialog(rootPane, "Passwords do not Match");
            }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane, "Upload Images only b/w 10kb to 900kb");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JFileChooser myfilechooser=new JFileChooser();
        myfilechooser.setFileFilter(new javax.swing.filechooser.FileFilter() {
            @Override
            public boolean accept(File f) {
                if(f.isDirectory())
                {
                    return true;
                }
                String extension=f.getName().substring(f.getName().lastIndexOf(".")+1);
                String allowed[]={"jpg","jpeg","gif","png"};
                for(String a:allowed)
                {
                    if(extension.equalsIgnoreCase(a))
                    {
                        return true;
                    }
                }
                return false;
            }
            @Override
            public String getDescription() 
            {
                return "All Picture Files";
            }
        });
          if(myfilechooser.showOpenDialog(this)==JFileChooser.APPROVE_OPTION)
            {
                try 
                {
                    myfile=myfilechooser.getSelectedFile();
                    Image simg = ImageIO.read(new File(myfile.getPath())).getScaledInstance(t6.getWidth(), t6.getHeight(), Image.SCALE_DEFAULT); 
                    t6.setIcon(new ImageIcon(simg));
                } 
                catch (Exception ex) 
                {
                System.out.println("Error occured while showing image due to " + ex.getMessage());
                }
            }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField t1;
    private javax.swing.JFormattedTextField t2;
    private javax.swing.JFormattedTextField t3;
    private javax.swing.JPasswordField t4;
    private javax.swing.JPasswordField t5;
    private javax.swing.JLabel t6;
    private javax.swing.JRadioButton t7;
    private javax.swing.JRadioButton t8;
    // End of variables declaration//GEN-END:variables
}
