/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lib.management;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.logging.*;
import javax.imageio.ImageIO;
import javax.swing.*;
import static lib.management.MyVariables.PASSWORD;
import static lib.management.MyVariables.PATH;
import static lib.management.MyVariables.PLACE;
import static lib.management.MyVariables.USERNAME;
/**
 *
 * @author THE BAD GUY
 */
public class NewMember extends javax.swing.JInternalFrame {

    File myfile;
    String imagename;
    public NewMember() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        t2 = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        t3 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        t4 = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        t5 = new javax.swing.JRadioButton();
        t6 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        t7 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        t8 = new com.toedter.calendar.JDateChooser();
        t9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setTitle("Add Member");

        jLabel1.setText("Name");

        jLabel2.setText("Age");

        t2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel3.setText("Class");

        t3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Ur Class", "B.Sc", "BBA", "B.Com", "B.Tech" }));

        jLabel4.setText("Roll No.");

        t4.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jLabel5.setText("Gender");

        buttonGroup1.add(t5);
        t5.setText("Male");

        buttonGroup1.add(t6);
        t6.setText("Female");

        jLabel6.setText("Address");

        t7.setColumns(20);
        t7.setRows(5);
        t7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t7KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(t7);

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\THE BAD GUY\\Documents\\NetBeansProjects\\lib management\\plus.png")); // NOI18N
        jButton1.setText("ADD MEMBER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setText("Date Of Birth");

        t9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jButton2.setText("Upload");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("*  Img Size must be b/w 10kb to 900kb.");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("*  Img Must be Cleared not Blured.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)))
                            .addComponent(jLabel7))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(t2)
                                            .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(t8, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(t5)
                                            .addGap(41, 41, 41)
                                            .addComponent(t6))
                                        .addComponent(t4, javax.swing.GroupLayout.Alignment.TRAILING)))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addComponent(t9, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(t8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(t6)
                                        .addComponent(jButton2))
                                    .addComponent(t5)))))
                    .addComponent(t9, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean flag=false;
 
        if(myfile!=null)
        {
            if(myfile.length()<900000&&myfile.length()>10000)
            {
                imagename=new java.util.Date().getTime() + myfile.getName();
                int i;

                FileInputStream rd = null;
                FileOutputStream outs = null;

                try 
                {
                    rd = new FileInputStream(myfile);
                    outs = new FileOutputStream("memberimages\\"+imagename);//writing the new file in 'Images' folder, in the project
                    byte[] b = new byte[2048]; //cache of 2kb
                    while ((i = rd.read(b)) !=-1) 
                    {
                        outs.write(b, 0, i); //copying from pictures to empimages byte by byte
                    }
                }
                catch (Exception e) 
                {
                    JOptionPane.showMessageDialog(rootPane, "error" + e.getMessage());
                } 
                    flag=true;
            }
            else
            {
                flag=false;
                JOptionPane.showMessageDialog(rootPane, "Upload Images only b/w 10kb to 900kb");
            }
        }
        else
        {
            if(t5.isSelected())
                imagename="defaultmale.jpg";
            else if(t6.isSelected())
                imagename="defaultfemale.png";
            flag=true;
        } 



        if(flag)
        {
            try
             {
                Connection myconnection=DriverManager.getConnection(PATH+PLACE,USERNAME,PASSWORD);
                try
                {
                    String myquery="insert into member(name,age,class,rollno,gender,address,dob,memberpic) values(?,?,?,?,?,?,?,?)";
                    PreparedStatement mystatement=myconnection.prepareStatement(myquery);
                    mystatement.setString(1, t1.getText());
                    mystatement.setString(2, t2.getText());
                    mystatement.setString(6, t7.getText());
                    mystatement.setString(4, t4.getText());
                    SimpleDateFormat a1=new SimpleDateFormat("yyyy-MM-dd");
                    mystatement.setString(7, a1.format(t8.getDate()));
                    mystatement.setString(3, t3.getSelectedItem().toString());

                    if(t5.isSelected())
                        mystatement.setString(5, "Male");
                    else if(t6.isSelected())
                        mystatement.setString(5, "Female");
                    mystatement.setString(8, imagename);
                    if(mystatement.executeUpdate()>0)
                    {
                        JOptionPane.showMessageDialog(rootPane, "Member Added Successfully");
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(rootPane, "Some Problem Occured");
                    }
                }
                catch(Exception et)
                {
                    JOptionPane.showMessageDialog(rootPane, "Error in querry due to "+et.getMessage());
                }
                finally
                {
                    myconnection.close();
                }
             }
             catch(Exception e)
             {
                 JOptionPane.showMessageDialog(rootPane, "Error in connection due to "+e.getMessage());
             }
        }
        else
        {
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void t7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t7KeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            jButton1.doClick();
        }
    }//GEN-LAST:event_t7KeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JFileChooser myfilechooser=new JFileChooser();
        myfilechooser.setFileFilter(new javax.swing.filechooser.FileFilter() {
            @Override
            public boolean accept(File f) {
                if(f.isDirectory())
                {
                    return true;
                }
                String extension=f.getName().substring(f.getName().lastIndexOf(".")+1);
                String allowed[]={"jpg","jpeg","gif","png"};
                for(String a:allowed)
                {
                    if(extension.equalsIgnoreCase(a))
                    {
                        return true;
                    }
                }
                return false;
            }
            @Override
            public String getDescription() 
            {
                return "All Picture Files";
            }
        });
          if(myfilechooser.showOpenDialog(this)==JFileChooser.APPROVE_OPTION)
            {
                try 
                {
                    myfile=myfilechooser.getSelectedFile();
                    Image simg = ImageIO.read(new File(myfile.getPath())).getScaledInstance(t9.getWidth(), t9.getHeight(), Image.SCALE_DEFAULT); 
                    t9.setIcon(new ImageIcon(simg));
                } 
                catch (Exception ex) 
                {
                System.out.println("Error occured while showing image due to " + ex.getMessage());
                }
            }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField t1;
    private javax.swing.JFormattedTextField t2;
    private javax.swing.JComboBox<String> t3;
    private javax.swing.JFormattedTextField t4;
    private javax.swing.JRadioButton t5;
    private javax.swing.JRadioButton t6;
    private javax.swing.JTextArea t7;
    private com.toedter.calendar.JDateChooser t8;
    private javax.swing.JLabel t9;
    // End of variables declaration//GEN-END:variables
}
